//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaitiKino.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Films
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> GenreId { get; set; }
        public Nullable<int> DurationInHours { get; set; }
    
        public virtual Genres Genres { get; set; }
    }
}
